#!/usr/bin/env bash
# Refresh src/assets/apps.json and open a PR against develop.
#
# develop is protected and requires the CI checks, so it can no longer be
# pushed to directly - which is what `npm run deploy` used to do. The data
# refresh now travels the same reviewed path as any other change.
#
# Note this is not the only way the site updates: deploy.yml re-fetches the
# data itself on every deploy and runs daily on a cron, so the live site stays
# current without this. What this adds is keeping the *committed* apps.json in
# step, which is what the e2e suite and PR CI assert against.
set -euo pipefail

if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "Working tree is dirty. Commit or stash first." >&2
  exit 1
fi

BRANCH="data/$(date +%Y-%m-%d-%H%M)"

# Branch off the current origin/develop, not whatever is checked out, so the
# PR carries the data refresh and nothing else.
git fetch origin develop
git checkout -b "$BRANCH" origin/develop

npm run fetch-data

if git diff --quiet -- src/assets/apps.json; then
  echo "apps.json is unchanged - nothing to deploy."
  echo "To redeploy the live site anyway: gh workflow run deploy.yml"
  git checkout -
  git branch -d "$BRANCH"
  exit 0
fi

git add src/assets/apps.json
git commit -m "data: refresh apps.json"
git push -u origin "$BRANCH"

gh pr create \
  --base develop \
  --head "$BRANCH" \
  --title "data: refresh apps.json" \
  --body "Regenerated by \`npm run deploy\` (\`npm run fetch-data\` → \`scripts/fetch-apps.mjs\`).

Merging this pushes develop, which deploys to Pages.

🤖 Generated with [Claude Code](https://claude.com/claude-code)"

echo
echo "PR opened. Merge it once CI is green - that is what deploys."
